417 PR
Lidemy/mentor-program-5th-yymarlerr pull request #1
Opened 2021-04-17 17:12 UTC by yymarlerr

2021-04-18 04:34 UTC, cwc329 requested changes

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/README.md
> +因此這個作業要請你寫一篇簡短的話文章，試圖教會 h0w 哥什麼是 command line 以及如何使用，並且要教他如何達成他想要的功能。
怎麼會改到 README.md？

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw1.md
> +6.  先下載支援 .md 檔的文字編輯器
其實有些人是用 vim、textpad 等軟體編輯，這些都沒有支援 markdown。

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw1.md
> +1. 用`git checkout -b <branch name>` 新開一個 branch
只有新開 branch 嗎？

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw1.md
> +2. 用`git commit -am "commit 的名稱"` 更新版本
有新增檔案的話會怎樣呢？

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw1.md
> +6.  將 <branch name> 合併進 master
這裡想表達的動作是 merge 嗎？
如果是的話這樣不是正確交作業的流程。

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw1.md
> +1. 助教看完作業後會按 merge
這會看狀況，
像我如果作業有沒有重大問題會讓你們看要自己 merge 之後開新 branch 訂正，或是在原本的 branch 訂正之後再 merge 也行。

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw1.md
> +2. 助教把遠端的 branch 刪掉，代表 branch 正式合到 master 中
其實沒有 merge 也可以刪掉 remote branch。
所以這兩件事並沒有因果或者等價關係。

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw3.md
> +6. 輸入`ls -al` 確認檔案有新增成功
`ls -al` 中的 `-al` 有點多餘，因為你不需要檢查隱藏的檔案。

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw4.md
> +* 若要將所有檔案都加入版本控制：`git add .`
如果上層的資料夾有新增檔案，這樣可以嗎？

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw4.md
> +#### `git commit -m"enter commit name"`
-m 與 "" 之間可以加空白，比較好閱讀。
'enter' 可以不用，另外可以用 `<>` 取代 '""'，這樣會比較清楚這邊是輸入使用者可以自訂的東西。
另外與 commit 有關的這段文字通常被叫做 commit message。

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw4.md
> +5. 若 main 也有新增 commit 並且不小心和 new 改到同個檔案，那會產生 conflicts。
更改到同一個檔案不一定會有 conflict。

2021-04-18 04:34 UTC, cwc329 commented on homeworks/week1/hw5.md
> +- 後端為網頁後台，負責邏輯運算、處理資料。
後台通常指可以讓網頁、網站管理員進入並且管理的介面，通常也會是一個網頁。
後台跟後端是不一樣的。

2021-04-18 04:39 UTC, cwc329 commented
hw1 與 hw5 建議再釐清流程與觀念。
可以自己 merge 之後開新的 branch 修改，或者直接在這個 PR 修改。
改好之後可以 tag 我，我會再來看。

2021-04-18 16:15 UTC, yymarlerr commented on homeworks/week1/README.md
> +因此這個作業要請你寫一篇簡短的話文章，試圖教會 h0w 哥什麼是 command line 以及如何使用，並且要教他如何達成他想要的功能。
不好意思我也還在思考為什麼⋯⋯

2021-04-18 16:15 UTC, yymarlerr commented on homeworks/week1/hw1.md
> +6.  先下載支援 .md 檔的文字編輯器
好的，了解，謝謝補充

2021-04-18 16:16 UTC, yymarlerr commented on homeworks/week1/hw1.md
> +1. 用`git checkout -b <branch name>` 新開一個 branch
沒有，還會 switch 到該分支

2021-04-18 16:16 UTC, yymarlerr commented on homeworks/week1/hw1.md
> +2. 用`git commit -am "commit 的名稱"` 更新版本
有新增檔案的話，需要先將新檔案加入版本控制，才能更新版本

2021-04-18 16:17 UTC, yymarlerr commented on homeworks/week1/hw1.md
> +6.  將 <branch name> 合併進 master
不好意思，發 PR 的目的是讓協作者知道有版本更新，然後請他們 approve

2021-04-18 16:17 UTC, yymarlerr commented on homeworks/week1/hw3.md
> +6. 輸入`ls -al` 確認檔案有新增成功
好的。

2021-04-18 16:18 UTC, yymarlerr commented on homeworks/week1/hw4.md
> +* 若要將所有檔案都加入版本控制：`git add .`
不行，因為 `.` 代表這個資料夾，所以上一層資料夾如果也有新增的話，要回到上一層資料夾去新增檔案

2021-04-18 16:18 UTC, yymarlerr commented on homeworks/week1/hw4.md
> +#### `git commit -m"enter commit name"`
好的，謝謝你

2021-04-18 16:19 UTC, yymarlerr commented on homeworks/week1/hw4.md
> +5. 若 main 也有新增 commit 並且不小心和 new 改到同個檔案，那會產生 conflicts。
好的，這邊描述應該要更清楚才對，是在 Git 無法判斷的情況下才會有衝突產生。

2021-04-18 16:20 UTC, yymarlerr commented on homeworks/week1/hw5.md
> +- 後端為網頁後台，負責邏輯運算、處理資料。
後來有去 google 後台管理，有比較清楚後台跟後端的差異了。

2021-04-18 16:24 UTC, yymarlerr commented
@cwc329 助教你好，我重新更新版本了，還請幫忙檢閱，謝謝你

2021-04-18 16:40 UTC, yymarlerr commented
助教你好，

有一個問題想要請教你，請問為什麼我在 branch <feature> 上新增了一個檔案 <test> 後，切到別的 branch <lalala>，<lalala> 也會有這個檔案：
![Imgur](https://i.imgur.com/RxVbbWa.png)

謝謝

2021-04-19 14:15 UTC, yymarlerr commented
> 助教你好，
> 
> 有一個問題想要請教你，請問為什麼我在 branch 上新增了一個檔案 後，切到別的 branch ， 也會有這個檔案：
> ![Imgur](https://camo.githubusercontent.com/75d7fe7ef477c0e33d3467cea9cbc403cfa9153ce360619e283c7d0eddb3735d/68747470733a2f2f692e696d6775722e636f6d2f527856626257612e706e67)
> 
> 謝謝

啊啊，不好意思，我發現我忘記先 commit 了。

2021-04-19 14:48 UTC, cwc329 commented
有訂正讚讚！
大致上沒有問題了，可以前往下一週

2021-04-19 14:48 UTC, merged