Week3
Lidemy/mentor-program-5th-yymarlerr pull request #3
Opened 2021-05-04 14:04 UTC by yymarlerr

2021-05-05 14:20 UTC, cwc329 requested changes
作業有達到基本要求，GJ。

不過請注意一下變數命名，
請盡量用具閱讀性、可理解的變數命名，
注意變數命名規則，
也要針對不同的變數型態改變命名。

還有 eslint 在目前階段不要 disable，
請依照 eslint 訊息更正程式碼，
訂正好之後再 push 一次，
然後 tag 我，我會再來看。

2021-05-05 14:20 UTC, cwc329 commented on homeworks/week3/hw1.js
> +/* eslint-disable */
為何要 eslint-disable？

2021-05-05 14:20 UTC, cwc329 commented on homeworks/week3/hw2.js
> +  const N = Number(a[0])
建議不用要單個英文字母作為變數命名，
另外如果是大寫開頭通常是 class，全部都是大寫通常是 global constant，
JS 慣例還是以 camel case 作為命名規則。

2021-05-05 14:20 UTC, cwc329 commented on homeworks/week3/hw2.js
> +function digitnumber(n) {
camel case。
另外 function 通常會以動詞開頭，或者包含動詞。

2021-05-05 14:20 UTC, cwc329 commented on homeworks/week3/hw3.js
> +const { isPrimitive } = require('util');
為何要 require 這個？

2021-05-05 14:20 UTC, cwc329 commented on homeworks/week3/hw5.js
> +    if (C === 1) {
這個判斷是有需要嗎？

2021-05-05 14:20 UTC, cwc329 commented on homeworks/week3/hw6.md
> +這邊在寫 bigOrsmall 函式時，一樣是先用判斷式，將取值大跟取值小的狀況分開來，然後分別在做判斷。
可以想一下不用 BigInt 要怎麼處理。

2021-05-05 14:20 UTC, cwc329 commented on homeworks/week3/hw6.md
> +[函式截圖連結] (https://imgur.com/72SB0FO)
下次可以用 code block 把程式碼放在這邊會比較好 review。

2021-05-05 14:20 UTC, cwc329 commented on homeworks/week3/hw6.md
> +[函式截圖連結] (https://imgur.com/72SB0FO)
應該是 `multiply` 有錯，
次方是用 `**` 不是 `*`。

2021-05-06 03:45 UTC, yymarlerr commented on homeworks/week3/hw1.js
> +/* eslint-disable */
因為前面一大段程式碼是直接複製過來的，我其實沒有花時間理解他在幹麻，覺得 eslint 完意義好像也不大（？）。不過會聽從助教的建議，現階段不使用 disable。

2021-05-06 03:56 UTC, yymarlerr commented on homeworks/week3/hw2.js
> +  const N = Number(a[0])
好的，謝謝助教提醒。
助教，想確認一下，你說的 class 是這個嗎：https://www.digitalocean.com/community/tutorials/understanding-classes-in-javascript

2021-05-06 03:56 UTC, yymarlerr commented on homeworks/week3/hw2.js
> +function digitnumber(n) {
好的，謝謝提醒。

2021-05-06 03:58 UTC, yymarlerr commented on homeworks/week3/hw3.js
> +const { isPrimitive } = require('util');
痾不好意思我現在才發現，應該是不小心複製錯的

2021-05-06 03:58 UTC, yymarlerr commented on homeworks/week3/hw5.js
> +    if (C === 1) {
好像是多餘的

2021-05-06 03:58 UTC, yymarlerr commented on homeworks/week3/hw6.md
> +這邊在寫 bigOrsmall 函式時，一樣是先用判斷式，將取值大跟取值小的狀況分開來，然後分別在做判斷。
好，我再想想。

2021-05-06 03:58 UTC, yymarlerr commented on homeworks/week3/hw6.md
> +[函式截圖連結] (https://imgur.com/72SB0FO)
好的。

2021-05-06 04:17 UTC, yymarlerr commented on homeworks/week3/hw6.md
> +[函式截圖連結] (https://imgur.com/72SB0FO)
了解次方是用 ** 沒錯，但還是不明白為什麼 multiply 有錯，目前輸入的值都會得到預期中的結果，可以請助教再提點一下嗎？感謝

`function multiply(a, b) {
  let result = 1
  for (let i = 1; i<= b; i++) {
    result = result * a
  }
  return result
} 
console.log(multiply(7, 3))`

==> 會回傳 7 的 3 次方 = 343

2021-05-08 09:49 UTC, cwc329 commented on homeworks/week3/hw2.js
> +  const N = Number(a[0])
對，就是這個。
不過現階段可以先不用管這個，隨著課程推進就會學到。

2021-05-08 10:03 UTC, cwc329 approved these changes
有訂正給推！
eslint 也有到位，不錯！
剩一些小問題，
可以自己斟酌進度看要不要回來修改。

對不起，
我在看程式碼的時候可能有疏忽，
沒有抓到其實 function 是沒問題的，
如果 function 功能如預期，
那可能是使用的時機有問題。
大概是這樣，
恭喜完成作業。

2021-05-08 10:03 UTC, cwc329 commented on homeworks/week3/hw2.js
> +function isNarcissistic(n) {
is 開頭的 function 回傳不是 boolean 值有點奇怪，
因為慣例會是 boolean。

2021-05-08 10:03 UTC, cwc329 commented on homeworks/week3/hw6.md
> +[函式截圖連結] (https://imgur.com/72SB0FO)
因為沒有看到你怎麼呼叫的，
不知道你是在哪裡用這個 function，
可能不是這個 function 的問題，
可能是你在不對的地方使用。
建議把整段程式碼貼上來，
這樣我比較好抓錯。

另外，
貼整段程式碼，
用 \`\`\` 把程式碼夾在中間，
可以去複習 markdown 語法。
成功的話應該會像這樣：
```
const test = 'testing';
```

2021-05-08 10:03 UTC, cwc329 commented on homeworks/week3/hw5.js
> +function bigOrsmall(a, b, c) {
建議不要使用 a, b, c 這樣單個英文字母作為變數命名，
雖然題目是這樣設定，
不過好的命名習慣應該要讓不用看到題目也能知道這個變數代表什麼意義。

2021-05-08 10:03 UTC, merged

2021-05-09 15:33 UTC, yymarlerr commented on homeworks/week3/hw6.md
> +[函式截圖連結] (https://imgur.com/72SB0FO)
好的。結果我再測試一次，答案就是正確的了，就不貼上來了，謝謝～～

2021-05-09 15:34 UTC, yymarlerr commented on homeworks/week3/hw2.js
> +function isNarcissistic(n) {
好的，謝謝助教！